package com.example.pantrypal.di

import com.example.pantrypal.BuildConfig // Import generated BuildConfig
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Named
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class) // Provides dependencies for the entire application lifecycle
object AppModule {

    @Provides
    @Singleton // Ensures a single instance of the API key string is provided
    @Named("openRouterApiKey") // Qualifier to distinguish this String from other String dependencies
    fun provideOpenRouterApiKey(): String {
        // Access the API key from the BuildConfig generated by Gradle
        return BuildConfig.OPENROUTER_API_KEY
    }

    // Other application-wide dependencies can be provided here in the future
}
